CFLAGS=-std=c99 -pedantic -Wall -O
CXXFLAGS=-static -pedantic -Wall -Weffc++ -Wextra -Wold-style-cast -O
STRIP=x86_64-w64-mingw32-strip
CC=x86_64-w64-mingw32-gcc
CXX=x86_64-w64-mingw32-g++
EXE_EXT=.exe
LIB_EXT=.dll

include Makefile.common
